string=' heLLO world '
print(string.capitalize())
print(string.title())
print(string.upper())
print(string.islower())
print(string.isupper())
print(string.isalpha())
print(string.isnumeric())
print(string.isalnum())
print(string.split())
print(string.partition('O'))
print(string.strip())
print(string.lstrip())
print(string.rsplit())
print(string.startswith(' '))
print(string.endswith(' '))
print(string.isspace())
